# Site settings
title: 在路上的技术笔记
email: belm@vip.qq.com
description: > # 永远不要停止学习，因为你的竞争对手永远不会
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.belmeng.com" # the base hostname & protocol for your site
twitter_username: beylm
github_username:  belm@vip.qq.com

# Build settings
markdown: kramdown
source:      _source
destination: _deploy