markdown: rdiscount
permalink: /:title/
url: http://www.belmeng.com
name: belmeng
author: belm
qq: 394356779
email: belm@vip.qq.com
duoshuo: belm
cnzz: 3003688
weibo: belmeng
github: belm
pygments: true
safe: true
paginate: 20
about: "这里是 belm 的个人博客，创建于 2009 年。开始使用了WordProess；2015年1月迁移到 Jekyll @ GitHub。<br /><br />这里包含了部分个人的“折腾”过程、结论和成果，切换到分类模可以更快地找到感兴趣的内容，欢迎观赏、建议、拍砖……"
